spring.application.name=scoutly

spring.datasource.url=jdbc:postgresql://localhost:5432/scoutly
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION:7200000}